<?php

namespace Integration\ZohoInvoicingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CurrenciesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrenciesRepository extends EntityRepository
{
}
