<?php

namespace Integration\ZohoInvoicingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxRepository extends EntityRepository
{
    
}